name: mdbapp
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^0.1.3
  http:
  bloc: ^3.0.0
  rxdart: ^0.23.1
  eva_icons_flutter: ^2.0.0
  flutter_rating_bar: ^3.0.1+1
  page_indicator: ^0.2.0
  font_awesome_flutter: ^8.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true